In [12]:
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X, Y)

print clf.predict([[-0.8, -1]])

[1]


In [13]:
print clf.predict([[-0.8, -1], [4, 5]])

[1 2]


In [17]:
print clf.predict_proba([[-0.8, -1]])

[[  9.99999949e-01   5.05653254e-08]]


In [18]:
print clf.predict_proba([[4, 5]])

[[  3.30570535e-37   1.00000000e+00]]


In [19]:
print clf.predict_proba([[-0.8, -1], [4, 5]])

[[  9.99999949e-01   5.05653254e-08]
 [  3.30570535e-37   1.00000000e+00]]


In [20]:
print clf.predict_proba([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])

[[  9.99999985e-01   1.52299840e-08]
 [  1.00000000e+00   3.77513581e-11]
 [  1.00000000e+00   5.74952589e-19]
 [  1.52299840e-08   9.99999985e-01]
 [  3.77513581e-11   1.00000000e+00]
 [  5.74952589e-19   1.00000000e+00]]


In [25]:
X = np.array([[-1, -1, -1], [-2, -1, -1], [-3, -2, -3], [1, 1, 1], [2, 1, 1], [3, 2, 3]])
Y = np.array([1, 1, 2, 2, 3, 3])

clf = GaussianNB()
clf.fit(X, Y)

print clf.predict([[-0.8, -1, -1]])

[1]


In [26]:
print clf.predict_proba([[-1, -1, -1], [-2, -1, -1], [-3, -2, -3], [1, 1, 1], [2, 1, 1], [3, 2, 3]])

[[  9.99999999e-01   6.06520247e-10   1.45869105e-26]
 [  9.99999999e-01   5.35252240e-10   1.64154101e-33]
 [  0.00000000e+00   1.00000000e+00   4.87463031e-41]
 [  0.00000000e+00   6.94649286e-01   3.05350714e-01]
 [  0.00000000e+00   2.18160067e-02   9.78183993e-01]
 [  0.00000000e+00   8.52109782e-04   9.99147890e-01]]


In [27]:
print clf.predict_log_proba([[-1, -1, -1], [-2, -1, -1], [-3, -2, -3], [1, 1, 1], [2, 1, 1], [3, 2, 3]])

[[ -6.06519279e-10  -2.12232830e+01  -5.94896729e+01]
 [ -5.35251843e-10  -2.13482830e+01  -7.54896726e+01]
 [ -5.35714267e+08   0.00000000e+00  -9.28219445e+01]
 [ -8.57142847e+08  -3.64348185e-01  -1.18629428e+00]
 [ -8.57142862e+08  -3.82511132e+00  -2.20574945e-02]
 [ -2.67857145e+09  -7.06779519e+00  -8.52473034e-04]]
